# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*' 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
        uses: docker/build-push-action@v2.6.1
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          # List of tags
          tags: ${{ steps.tagName.outputs.tag }}
